# Generated by Django 4.2.11 on 2024-04-14 21:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
